name: Deploy to GitHub Pages

# Triggers the workflow on push to main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4
        
      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      # Install wasm-tools workload for Blazor WebAssembly
      - name: Install wasm-tools
        run: dotnet workload install wasm-tools
        
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
        
      # Build the Blazor WebAssembly project
      - name: Build
        run: dotnet publish -c Release -o publish
        
      # Change base href in index.html for GitHub Pages subdirectory
      - name: Change base href
        run: sed -i 's/<base href="\/" \/>/<base href="\/InGeorgianLari\/" \/>/g' publish/wwwroot/index.html
        
      # Fix 404 for client-side routing by copying index.html to 404.html
      - name: Copy index.html to 404.html
        run: cp publish/wwwroot/index.html publish/wwwroot/404.html
        
      # Add .nojekyll file to bypass Jekyll processing
      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll
        
      # Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/wwwroot

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4